emails = tuple()
username = tuple()
domainname = tuple()
n = int(input("How many Email-IDs do you want to enter? :"))
for i in range(0,n):
    emid = input("> ")
    emails = emails +(emid,)
    spl= emid.split("@")
    username = username + (spl[0],)
    domainname = domainname + (spl[1],)
print("\nThe Email-IDs you entered are :")
print(emails)
print("\nTHe username in the Email-IDs are :")
print(username)
print("\nThe domain names in the Email-IDs are :")
print(domainname)